### ISSUE TITLE
Include review text in review messages

### ISSUE THREAD

**Issue by KnorpelSenf** [roj1512/ghb#2]
When a pull request is reviewed, it looks like this:

> @KnorpelSenf reviewed website#777 Rename section to “Serverless and PaaS” and add a paragraph explaining PaaS.

I'd like to see the review text.

**Comment by rojvv** [comment]
I don’t believe this is possible. The behavior when a `pull_request_review` event is received with its `review.state` being `commented` is not documented.

<img width="270" alt="Screenshot 2023-05-28 at 5 44 53 PM" src="https://github.com/roj1512/ghb/assets/49933115/8ef2c088-2335-4a01-8e38-c2b211b096ed">

<img width="473" alt="Screenshot 2023-05-28 at 5 44 10 PM" src="https://github.com/roj1512/ghb/assets/49933115/e09aa745-9a45-4da4-97e3-c79cf5fd4011">

**Comment by KnorpelSenf** [comment]
Is there a way to fetch the comment?

**Comment by rojvv** [comment]
Enlighten me.

**Comment by rojvv** [comment]
There is no proper reference to the comment itself I think.

**Comment by KnorpelSenf** [comment]
https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#get-a-review-comment-for-a-pull-request maybe?

**Comment by KnorpelSenf** [comment]
Whoop whoop
